-- Expand body-region coverage: reclassify legacy "back" exercises and add catalog entries
-- for chest, elbows, wrists, core, glutes, thighs, calves, and ankles/feet.

UPDATE public.exercises SET body_region = 'lower_back' WHERE name IN (
  'Cat-cow', 'Child''s pose', 'Bird dog', 'Pelvic tilt', 'Superman hold'
);
UPDATE public.exercises SET body_region = 'upper_back' WHERE name IN (
  'Thoracic rotation', 'Seated spinal twist', 'Scapular retraction'
);
UPDATE public.exercises SET body_region = 'core' WHERE name IN (
  'Dead bug', 'Side plank', 'Plank hold'
);
UPDATE public.exercises SET body_region = 'chest' WHERE name = 'Doorway chest stretch';
UPDATE public.exercises SET body_region = 'glutes' WHERE name IN (
  'Glute bridge', 'Clamshell'
);
UPDATE public.exercises SET body_region = 'thighs' WHERE name IN (
  'Hamstring stretch', 'Step-ups'
);
UPDATE public.exercises SET body_region = 'calves' WHERE name IN (
  'Calf stretch', 'Standing calf raise'
);
UPDATE public.exercises SET body_region = 'ankles_feet' WHERE name = 'Ankle pumps';

-- Remaining legacy "back" rows become lower back by default.
UPDATE public.exercises SET body_region = 'lower_back' WHERE body_region = 'back';

INSERT INTO public.exercises (
  name, body_region, exercise_type, difficulty, equipment,
  instructions, sets_reps, duration_minutes, benefits, contraindications
)
SELECT v.* FROM (VALUES
  ('Thread the needle', 'upper_back', 'mobility', 'iniciante', ARRAY['mat']::text[],
    'On hands and knees, slide one arm under the body and rotate the upper back gently.',
    'Hold 20 seconds per side', 6,
    'Improves thoracic rotation and upper-back mobility.',
    'Move slowly and stay within a pain-free range.'),
  ('Rhomboid squeeze', 'upper_back', 'strength', 'iniciante', ARRAY['none']::text[],
    'Sit or stand tall and squeeze shoulder blades together without shrugging.',
    '2 sets of 12 reps', 5,
    'Strengthens postural muscles between the shoulder blades.',
    'Keep neck relaxed.'),
  ('Prone T raise', 'upper_back', 'strength', 'intermediario', ARRAY['mat']::text[],
    'Lie face down and lift arms out to a T shape while squeezing shoulder blades.',
    '2 sets of 8 reps', 8,
    'Targets mid-back and rear shoulder stability.',
    'Use small lifts only.'),
  ('Lat stretch on chair', 'upper_back', 'stretch', 'iniciante', ARRAY['chair']::text[],
    'Sit on a chair, place one hand on the seat, and side-bend to stretch the side of the back.',
    'Hold 20 seconds per side', 5,
    'Opens the lats and side trunk.',
    'Avoid if shoulder pain is acute.'),

  ('Knee-to-chest stretch', 'lower_back', 'stretch', 'iniciante', ARRAY['mat']::text[],
    'Lie on your back and gently pull one knee toward your chest.',
    'Hold 30 seconds per side', 6,
    'Relieves lower-back tension.',
    'Stop if sharp pain increases.'),
  ('Supine lumbar rotation', 'lower_back', 'mobility', 'iniciante', ARRAY['mat']::text[],
    'Lie on your back with knees bent and let both knees fall slowly to one side.',
    'Hold 20 seconds per side', 6,
    'Adds gentle rotation to the lumbar spine.',
    'Keep both shoulders on the floor.'),
  ('Prone press-up', 'lower_back', 'mobility', 'intermediario', ARRAY['mat']::text[],
    'Lie on your stomach and press up through the arms while hips stay low.',
    '2 sets of 8 reps', 8,
    'Encourages extension mobility in the lower back.',
    'Skip if extension aggravates symptoms.'),

  ('Corner pec stretch', 'chest', 'stretch', 'iniciante', ARRAY['none']::text[],
    'Place forearms on a wall corner and lean forward until you feel a chest stretch.',
    'Hold 30 seconds', 5,
    'Opens the chest and front shoulders.',
    'Use a smaller angle if shoulder pain appears.'),
  ('Standing chest opener', 'chest', 'mobility', 'iniciante', ARRAY['none']::text[],
    'Clasp hands behind your back and lift the chest gently while opening the front body.',
    'Hold 20 seconds, 3 reps', 5,
    'Counteracts rounded posture.',
    'Do not force the arms upward.'),
  ('Band chest stretch', 'chest', 'stretch', 'iniciante', ARRAY['band']::text[],
    'Hold a band behind you with arms straight and gently pull the band away from the body.',
    'Hold 20 seconds, 2 reps', 5,
    'Stretches chest and front shoulders with light resistance.',
    'Use light tension only.'),
  ('Wall push-up plus', 'chest', 'strength', 'iniciante', ARRAY['none']::text[],
    'Perform a wall push-up and finish by pushing shoulder blades apart at the end range.',
    '2 sets of 10 reps', 8,
    'Builds chest and serratus control safely.',
    'Keep wrists aligned with shoulders.'),

  ('Triceps stretch', 'elbows', 'stretch', 'iniciante', ARRAY['none']::text[],
    'Reach one hand down the middle of your back and gently press the elbow with the other hand.',
    'Hold 20 seconds per side', 5,
    'Stretches the back of the upper arm and elbow area.',
    'Do not force the elbow downward.'),
  ('Forearm stretch', 'elbows', 'stretch', 'iniciante', ARRAY['none']::text[],
    'Extend one arm with palm up and gently pull the fingers back with the other hand.',
    'Hold 20 seconds per side', 5,
    'Relieves forearm and elbow tension.',
    'Stop if numbness increases.'),
  ('Elbow circles', 'elbows', 'mobility', 'iniciante', ARRAY['none']::text[],
    'Bend the elbow and make slow circles with the forearm.',
    '10 circles each direction per arm', 5,
    'Lubricates the elbow joint for daily movement.',
    'Keep circles small if pain appears.'),
  ('Isometric elbow bend', 'elbows', 'strength', 'iniciante', ARRAY['none']::text[],
    'Place the palm against the opposite hand and press gently without moving the elbow.',
    'Hold 5 seconds, 8 reps per side', 5,
    'Builds elbow stability with low load.',
    'Use light pressure only.'),

  ('Prayer stretch', 'wrists_hands', 'stretch', 'iniciante', ARRAY['none']::text[],
    'Place palms together in front of the chest and lower hands while keeping palms touching.',
    'Hold 20 seconds', 5,
    'Stretches wrists and forearm flexors.',
    'Stop if sharp wrist pain occurs.'),
  ('Wrist extensor stretch', 'wrists_hands', 'stretch', 'iniciante', ARRAY['none']::text[],
    'Extend one arm palm down and gently pull the fingers toward you with the other hand.',
    'Hold 20 seconds per side', 5,
    'Relieves typing and phone-related wrist tension.',
    'Keep the stretch mild.'),
  ('Wrist flexor stretch', 'wrists_hands', 'stretch', 'iniciante', ARRAY['none']::text[],
    'Extend one arm palm up and gently pull the fingers down with the other hand.',
    'Hold 20 seconds per side', 5,
    'Balances forearm flexibility for wrist health.',
    'Avoid aggressive pulling.'),
  ('Finger spread and squeeze', 'wrists_hands', 'mobility', 'iniciante', ARRAY['none']::text[],
    'Open the fingers wide, hold briefly, then make a gentle fist.',
    '2 sets of 10 reps', 5,
    'Improves hand circulation and dexterity.',
    'Do not squeeze painfully tight.'),
  ('Wrist circles', 'wrists_hands', 'mobility', 'iniciante', ARRAY['none']::text[],
    'Make slow circles with the wrists in both directions.',
    '10 circles each direction', 5,
    'Warms up wrists before activity.',
    'Keep movement smooth.'),

  ('Bicycle crunch', 'core', 'strength', 'intermediario', ARRAY['mat']::text[],
    'Lie on your back and alternate bringing opposite elbow toward knee with control.',
    '2 sets of 10 reps per side', 8,
    'Builds rotational core strength.',
    'Keep lower back from arching excessively.'),
  ('Heel taps', 'core', 'strength', 'iniciante', ARRAY['mat']::text[],
    'Lie on your back with knees bent and alternately tap one heel to the floor.',
    '2 sets of 12 reps per side', 8,
    'Trains core stability during leg movement.',
    'Press lower back gently toward the floor.'),
  ('Dead bug hold', 'core', 'strength', 'iniciante', ARRAY['mat']::text[],
    'On your back, raise arms and legs to tabletop and hold while breathing steadily.',
    'Hold 15-20 seconds, 3 reps', 6,
    'Builds deep core endurance.',
    'Keep ribs down and back flat.'),
  ('Standing march with brace', 'core', 'mobility', 'iniciante', ARRAY['none', 'chair']::text[],
    'Stand tall near support and march slowly while keeping your trunk stable.',
    '2 sets of 20 steps', 5,
    'Connects core control to walking.',
    'Hold support if needed.'),

  ('Donkey kick', 'glutes', 'strength', 'iniciante', ARRAY['mat']::text[],
    'On hands and knees, lift one bent leg toward the ceiling while keeping hips square.',
    '2 sets of 12 reps per side', 8,
    'Activates glutes with low spinal load.',
    'Avoid arching the lower back.'),
  ('Fire hydrant', 'glutes', 'strength', 'iniciante', ARRAY['mat']::text[],
    'On hands and knees, lift the knee out to the side while keeping the trunk still.',
    '2 sets of 10 reps per side', 8,
    'Strengthens hip abductors and glutes.',
    'Move within a controlled range.'),
  ('Single-leg glute bridge', 'glutes', 'strength', 'intermediario', ARRAY['mat']::text[],
    'Perform a glute bridge with one foot lifted off the floor.',
    '2 sets of 8 reps per side', 8,
    'Increases glute challenge and hip stability.',
    'Keep hips level.'),
  ('Standing glute squeeze', 'glutes', 'strength', 'iniciante', ARRAY['none']::text[],
    'Stand tall and squeeze one glute firmly, hold, then release.',
    'Hold 5 seconds, 10 reps per side', 5,
    'Reactivates glutes after sitting.',
    'Hold support if balance is limited.'),

  ('Standing quad stretch', 'thighs', 'stretch', 'iniciante', ARRAY['none', 'chair']::text[],
    'Stand near support, bend one knee, and hold the ankle toward the glute.',
    'Hold 30 seconds per side', 6,
    'Stretches the front of the thigh.',
    'Keep knees close together.'),
  ('Adductor stretch', 'thighs', 'stretch', 'iniciante', ARRAY['mat']::text[],
    'Sit with soles of feet together and gently press knees toward the floor.',
    'Hold 30 seconds', 6,
    'Opens inner thighs and groin.',
    'Use cushions under knees if needed.'),
  ('Lateral lunge', 'thighs', 'mobility', 'intermediario', ARRAY['none']::text[],
    'Step wide to one side, bend that knee, and keep the other leg straight.',
    '2 sets of 8 reps per side', 8,
    'Improves side-to-side leg mobility.',
    'Only lunge as deep as comfortable.'),
  ('Standing hamstring curl', 'thighs', 'strength', 'iniciante', ARRAY['none', 'chair']::text[],
    'Stand tall and bend one knee to bring the heel toward the glute without leaning forward.',
    '2 sets of 10 reps per side', 6,
    'Builds hamstring control for walking.',
    'Hold support if needed.'),
  ('Wall sit with ball squeeze', 'thighs', 'strength', 'intermediario', ARRAY['none']::text[],
    'Hold a wall sit while optionally squeezing a pillow between the knees.',
    'Hold 20 seconds, 3 reps', 8,
    'Builds thigh endurance and inner-leg control.',
    'Keep knees aligned over ankles.'),

  ('Soleus stretch', 'calves', 'stretch', 'iniciante', ARRAY['none']::text[],
    'Stand facing a wall with one foot back, knee bent, and heel down to stretch the lower calf.',
    'Hold 30 seconds per side', 5,
    'Targets the deeper calf muscle used in walking.',
    'Keep back heel on the floor.'),
  ('Seated calf raise', 'calves', 'strength', 'iniciante', ARRAY['chair']::text[],
    'Sit tall and rise onto the balls of the feet, then lower slowly.',
    '2 sets of 15 reps', 5,
    'Strengthens calves with support and balance.',
    'Use armrests if needed.'),
  ('Towel calf stretch', 'calves', 'stretch', 'iniciante', ARRAY['mat']::text[],
    'Loop a towel around the ball of the foot and gently pull the toes toward you.',
    'Hold 30 seconds per side', 5,
    'Deepens calf stretch safely while seated.',
    'Pull gently, not forcefully.'),

  ('Ankle alphabet', 'ankles_feet', 'mobility', 'iniciante', ARRAY['none']::text[],
    'Trace the alphabet in the air with your foot while seated.',
    '1 alphabet per foot', 5,
    'Improves ankle mobility in all directions.',
    'Keep movements smooth.'),
  ('Toe curls', 'ankles_feet', 'strength', 'iniciante', ARRAY['none']::text[],
    'While seated, curl the toes down as if grabbing the floor, then release.',
    '2 sets of 12 reps', 5,
    'Strengthens foot intrinsic muscles.',
    'Relax between reps.'),
  ('Plantar fascia stretch', 'ankles_feet', 'stretch', 'iniciante', ARRAY['none']::text[],
    'Cross one ankle over the opposite knee and pull the toes back toward the shin.',
    'Hold 30 seconds per side', 6,
    'Relieves bottom-of-foot tightness.',
    'Stop if pain spikes sharply.'),
  ('Heel-to-toe walk', 'ankles_feet', 'mobility', 'iniciante', ARRAY['none', 'chair']::text[],
    'Walk slowly placing the heel down first, then roll through to the toes.',
    '2 passes of 10 steps', 5,
    'Improves foot and ankle coordination.',
    'Use wall support if balance is limited.'),
  ('Towel scrunches', 'ankles_feet', 'strength', 'iniciante', ARRAY['none']::text[],
    'Place a towel on the floor and scrunch it toward you using only your toes.',
    '2 sets of 10 scrunches', 5,
    'Builds arch and toe strength.',
    'Keep heel on the floor.')
) AS v(
  name, body_region, exercise_type, difficulty, equipment,
  instructions, sets_reps, duration_minutes, benefits, contraindications
)
WHERE NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.name = v.name);
